apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cfdapp4034-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cfdapp4034
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
