# Deployment for cfdappserver
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfdappserver
  labels:
    app: cfdappserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfdappserver
  template:
    metadata:
      labels:
        app: cfdappserver
    spec:
      containers:
        - name: cfdappserver
          image: 730335668847.dkr.ecr.us-east-1.amazonaws.com/cfdappserver:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
