# Deployment for cfdapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfdapp4034
  labels:
    app: cfdapp4034
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfdapp4034
  template:
    metadata:
      labels:
        app: cfdapp4034
    spec:
      containers:
        - name: cfdapp4034
          image: chargaoshou/cfdapp4034:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
