# Deployment for cfdapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfdapp4034
  labels:
    app: cfdapp4034
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfdapp4034
  template:
    metadata:
      labels:
        app: cfdapp4034
    spec:
      containers:
        - name: cfdapp4034
          image: 730335668847.dkr.ecr.us-east-1.amazonaws.com/cfdapp4034:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
