- hosts: k8s_nodes
  become: yes

  tasks:
    - name: Clone the repository
      git:
        repo: "https://github.com/apatel2582/BCDV_4034_Project_CF_DApp_Polygon_Group_09.git"
        dest: "./BCDV_4034_Project_CF_DApp_Polygon_Group_09"
        clone: yes
        update: yes

    - name: Debug OS Family
      debug:
        msg: "OS family is {{ ansible_os_family }}"

    - name: Ensure Python3 pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install Docker Python library
      pip:
        name: docker
        state: present

    - name: Build and run Docker container
      docker_compose:
        project_src: "./BCDV_4034_Project_CF_DApp_Polygon_Group_09"
        state: present
        build: yes
