plugin: gcp_compute
projects:
  - apt-vine-417512
auth_kind: serviceaccount
service_account_file: /home/andyshriller/apt-vine-417512-aa52621a2c12.json
scopes:
  - https://www.googleapis.com/auth/compute
filters: []
groups:
  k8s_nodes: "'gke' in name"
keyed_groups:
  - prefix: gcp
    key: labels
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
